# Generated by Django 2.2.5 on 2019-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(max_length=255)),
                ('Firstname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Bloodgroup', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Emailaddress', models.CharField(max_length=255)),
            ],
        ),
    ]
