# Generated by Django 2.2.5 on 2019-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Experience',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
