# Generated by Django 2.2.5 on 2019-09-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Assignedclass',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='Phonenumber',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
